update for StrOrPromise in typeddjango/django-stubs
typeddjango/djangorestframework-stubs pull request #301
Opened 2022-11-28 16:15 UTC by terencehonles

# I have made things!

StrOrPromise updates after https://github.com/typeddjango/django-stubs/pull/689

## Related issues

2022-12-03 10:49 UTC, intgr requested changes
Thanks! I rebased this to fix the CI issues on master.

But a few `.yml` test cases need to be updated in this branch as well, since mypy messages changed.

2022-12-03 10:50 UTC, intgr commented on rest_framework-stubs/fields.pyi
> +from django_stubs_ext import StrOrPromise
Ah also: please add explicit `django-stubs-ext` dependency to `setup.py`.

2023-01-27 19:52 UTC, piotrszyma commented
> @terencehonles Are you up to it to fix the CI here?

It seems like author has abandoned the PR and project I maintain needs DRF stubs bump - I've fixed tests and created a new PR here https://github.com/typeddjango/djangorestframework-stubs/pull/331

2023-02-03 16:37 UTC, intgr approved these changes
Great! I've force pushed @piotrszyma 's test fixes from #331. I'll add a `Co-authored-by:` tag though.

2023-02-03 16:38 UTC, merged

2023-02-10 15:55 UTC, terencehonles commented
Thanks for taking care of this, I have been rather busy and didn't notice the notifications.